name: Otomatik Derleme

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Kodu Klonla
      uses: actions/checkout@v4

    - name: .NET Framework ve MSBuild Kurulumu
      uses: microsoft/setup-msbuild@v2

    - name: NuGet Kurulumu
      uses: NuGet/setup-nuget@v2

    - name: Paketleri Yeniden Yükle
      run: nuget restore REE.PAK.Tool.sln

    - name: MSBuild ile Derle
      run: msbuild REE.PAK.Tool.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Dosyalari Yukle
      uses: actions/upload-artifact@v4
      with:
        name: REE-PAK-Tool-Derlenmis
        path: |
          **/bin/Release/*.exe
          **/bin/Release/*.dll
