name: CI Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Kodu sunucuya indirir
    - name: Checkout repository
      uses: actions/checkout@v4

    # MSBuild ve NuGet araçlarını kurar
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
      with:
        nuget-version: 'latest'

    # Bağımlılıkları yükler
    - name: Restore NuGet Packages
      run: |
        nuget restore REE.Fonts.Cryptor/REE.Fonts.Cryptor.sln
        nuget restore REE.Packer/REE.Packer.sln
        nuget restore REE.Rom.Cryptor/REE.Rom.Cryptor.sln
        nuget restore REE.Unpacker/REE.Unpacker.sln

    # Projeyi derler
    - name: Build Solution
      run: msbuild /p:Configuration=Release

    # Geliştirilmiş Arama: Klasör yapısı ne olursa olsun tüm EXE ve DLL dosyalarını bulur
    - name: Derleme Ciktilarini Sunucuya Yukle
      uses: actions/upload-artifact@v4
      with:
        name: REE-PAK-Tool-Ciktilari
        path: |
          **/*.exe
          **/*.dll
