name: Otomatik Derleme

on:
  workflow_dispatch: # Manuel olarak başlatabilmek için

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Kodu Klonla
      uses: actions/checkout@v4

    - name: MSBuild Kurulumu
      uses: microsoft/setup-msbuild@v2

    - name: Nuget Paketlerini Yukle
      uses: NuGet/setup-nuget@v2
      with:
        nuget-version: 'latest'

    - name: Paketleri Geri Yukle (Restore)
      run: nuget restore REE.PAK.Tool.sln

    - name: Projeyi Derle (Build)
      run: msbuild REE.PAK.Tool.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Hazir Dosyalari Paketle (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: REE-PAK-Tool-Derlenmis
        path: |
          **/bin/Release/**/*.exe
          **/bin/Release/**/*.dll
